		function show(){
			var val1=document.getElementById("first").value;
			var val2=document.getElementById("second").value;
			if(val1=="Bca" && val2=="1st"){
				document.getElementById("bca1").style.display="table";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Bca" && val2=="2nd"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="table";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Bca" && val2=="3rd"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="table";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Bca" && val2=="4th"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="table";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Bca" && val2=="5th"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="table";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Bca" && val2=="6th"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="table";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Mca" && val2=="1st"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="table";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Mca" && val2=="2nd"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="table";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Mca" && val2=="3rd"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="table";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Mca" && val2=="4th"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="table";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Mca" && val2=="5th"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="table";
				document.getElementById("mca6").style.display="none";
			}
			if(val1=="Mca" && val2=="6th"){
				document.getElementById("bca1").style.display="none";
				document.getElementById("bca2").style.display="none";
				document.getElementById("bca3").style.display="none";
				document.getElementById("bca4").style.display="none";
				document.getElementById("bca5").style.display="none";
				document.getElementById("bca6").style.display="none";
				document.getElementById("mca1").style.display="none";
				document.getElementById("mca2").style.display="none";
				document.getElementById("mca3").style.display="none";
				document.getElementById("mca4").style.display="none";
				document.getElementById("mca5").style.display="none";
				document.getElementById("mca6").style.display="table";
			}
		}